import { schemaToJsonSchema } from '../schema-utils'
import type { Step } from '../types'
import type { Stream } from '../types-stream'
import { generateTypeFromSchema } from './generate-type-from-schema'

export const generateStreamsInterface = (streams: Record<string, Stream>): string => {
  const entries = Object.entries(streams)
    .filter(([_, stream]) => !stream.hidden)
    .map(([name, stream]) => {
      const jsonSchema = schemaToJsonSchema(stream.config.schema)
      const type = jsonSchema ? generateTypeFromSchema(jsonSchema) : 'unknown'
      return `    ${name}: MotiaStream<${type}>`
    })
  
  return entries.length > 0
    ? `  interface Streams {\n${entries.join('\n')}\n  }`
    : `  interface Streams {}`
}

export const generateEmitsInterface = (steps: Step[]): string => {
  const emitTypes: Record<string, string> = {}
  
  for (const step of steps) {
    if ('emits' in step.config) {
      step.config.emits.forEach(emit => {
        const topic = typeof emit === 'string' ? emit : emit.topic
        if (!emitTypes[topic]) {
          emitTypes[topic] = 'unknown'
        }
      })
    }
    if ('subscribes' in step.config && step.config.subscribes) {
      step.config.subscribes.forEach(topic => {
        if (!emitTypes[topic] && 'input' in step.config && step.config.input) {
          const jsonSchema = schemaToJsonSchema(step.config.input)
          const type = jsonSchema ? generateTypeFromSchema(jsonSchema) : 'unknown'
          emitTypes[topic] = type
        }
      })
    }
  }
  
  const entries = Object.entries(emitTypes)
    .map(([topic, type]) => `    '${topic}': ${type}`)
  
  return entries.length > 0 
    ? `  interface Emits {\n${entries.join('\n')}\n  }`
    : `  interface Emits {}`
}

export const generateTypesString = (
  steps: Step[],
  streams: Record<string, Stream>,
): string => {
  const streamsInterface = generateStreamsInterface(streams)
  const emitsInterface = generateEmitsInterface(steps)
  
  return `/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 */
import { MotiaStream } from '@iii-dev/motia'

declare module '@iii-dev/motia' {
${streamsInterface}

${emitsInterface}
}
`
}

