/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 */
import { MotiaStream } from '@iii-dev/motia'

declare module '@iii-dev/motia' {
  interface Streams {
    todo: MotiaStream<{ id: string; description: string; createdAt: string; dueDate?: string; completedAt?: string }>
    inbox: MotiaStream<{ watching: number }>
  }

  interface Emits {}
}
