/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 *
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    todo: MotiaStream<{ id: string; description: string; createdAt: string; dueDate?: string; completedAt?: string }>
  }

  interface Handlers {
    UpdateTodo: ApiRouteHandler<
      { description?: string; dueDate?: string; checked?: boolean },
      | ApiResponse<200, { id: string; description: string; createdAt: string; dueDate?: string; completedAt?: string }>
      | ApiResponse<404, { error: string }>,
      never
    >
    DeleteTodo: ApiRouteHandler<
      Record<string, unknown>,
      ApiResponse<200, { id: string }> | ApiResponse<404, { error: string }>,
      never
    >
    CreateTodo: ApiRouteHandler<
      { description: string; dueDate?: string },
      | ApiResponse<200, { id: string; description: string; createdAt: string; dueDate?: string; completedAt?: string }>
      | ApiResponse<400, { error: string }>,
      never
    >
  }
}
