workers: {}

stacks:
  default:
    namespace: production
    containers:
      http:
        worker: package://api.workers.iii.dev/http@0.21.3
        config:
          host: 0.0.0.0
          port: 3111
      cron:
        worker: package://api.workers.iii.dev/cron@0.21.9
