import type { Sender, Step } from './types';

const alex: Sender = {
  name: 'Alex',
  role: 'Product Lead',
};

export const homepageFlow: Step[] = [
  // ── Beat 1: Python classifier worker ────────────────────────────────
  {
    id: 'msg-1',
    type: 'slack-message',
    sender: alex,
    content:
      'We need to classify user-submitted content for toxicity before it goes live. Can you set something up?',
    action: { label: 'Start ticket', count: 1 },
    delay: 500,
  },
  {
    id: 'reply-1',
    type: 'reply',
    content: "Sure, I'll write a Python classifier as a iii worker.",
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'code-1',
    type: 'code-editor',
    filename: 'content_classifier.py',
    language: 'python',
    lines: [
      'from iii import register_worker, InitOptions, Logger',
      '',
      "iii = register_worker(os.environ['III_ENGINE_URL'], InitOptions(",
      "    worker_name='content-classifier',",
      '))',
      'logger = Logger()',
      '',
      'def classify(payload: dict) -> dict:',
      "    text = payload.get('text', '')",
      "    logger.info(f'Classifying content: {text[:50]}...')",
      '    score = toxicity_model.predict(text)',
      "    return { 'label': 'toxic' if score > 0.7 else 'safe', 'score': score }",
      '',
      "iii.register_function('content::classify', classify)",
    ],
    doneLabel: 'Deploy',
    delay: 300,
  },
  {
    id: 'status-1',
    type: 'status',
    variant: 'info',
    icon: 'connect',
    headline: 'Classifier worker connected',
    detail: 'content::classify registered with the engine',
    autoAdvance: 1400,
    delay: 200,
  },

  // ── Beat 2: TS router, cross-language + durable publish ─────────────
  {
    id: 'msg-2',
    type: 'slack-message',
    sender: alex,
    content:
      'Great. Now we need to auto-approve clean content and flag toxic content for human review.',
    autoAdvance: 1500,
    delay: 500,
  },
  {
    id: 'reply-2',
    type: 'reply',
    content: "I'll create a TypeScript router that calls the classifier.",
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'msg-2b',
    type: 'slack-message',
    sender: alex,
    content:
      'How long is that going to take? Do we need an API for the Python worker?',
    autoAdvance: 1500,
    delay: 500,
  },
  {
    id: 'reply-2b',
    type: 'reply',
    content: "No, it's already connected since we're using iii.",
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'code-2',
    type: 'code-editor',
    filename: 'content-router.ts',
    language: 'typescript',
    lines: [
      "import { registerWorker } from 'iii-sdk'",
      '',
      'const iii = registerWorker(process.env.III_ENGINE_URL, {',
      "  workerName: 'content-router',",
      '})',
      '',
      "iii.registerFunction('content::route', async ({ text, authorId }) => {",
      '  const { label, score } = await iii.trigger({',
      "    function_id: 'content::classify',",
      '    payload: { text },',
      '  })',
      "  const topic = label === 'safe' ? 'comment.publish' : 'comment.review'",
      '  iii.trigger({',
      "    function_id: 'iii::durable::publish',",
      '    payload: { topic, data: { text, authorId, label, score } },',
      '  })',
      '})',
    ],
    doneLabel: 'Deploy',
    delay: 300,
  },
  {
    id: 'status-2',
    type: 'status',
    variant: 'info',
    icon: 'connect',
    headline: 'Content router live',
    detail:
      'Classifying cross-language, publishing to comment.publish and comment.review',
    autoAdvance: 1400,
    delay: 200,
  },

  // ── Beat 3: Add state ───────────────────────────────────────────────
  {
    id: 'msg-3',
    type: 'slack-message',
    sender: alex,
    content:
      'Can we track how many times each author gets flagged? We need moderation history.',
    autoAdvance: 1500,
    delay: 500,
  },
  {
    id: 'reply-3',
    type: 'reply',
    content: "I'll add state.",
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'terminal-3a',
    type: 'terminal-command',
    command: 'iii worker add iii-state',
    output: '✓ Worker iii-state installed',
    delay: 400,
  },
  {
    id: 'msg-3b',
    type: 'slack-message',
    sender: alex,
    content: 'How long to roll that out?',
    autoAdvance: 1500,
    delay: 500,
  },
  {
    id: 'reply-3b',
    type: 'reply',
    content: "It's done, adding the author history tracking now.",
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'code-3',
    type: 'code-editor',
    filename: 'content_classifier.py',
    language: 'python',
    lines: [
      'def on_flagged(event: dict) -> None:',
      "    author_id = event.get('author_id')",
      "    flags = iii.trigger({ 'function_id': 'state::get',",
      "        'payload': { 'scope': 'moderation', 'key': f'flags:{author_id}' } })",
      "    iii.trigger({ 'function_id': 'state::set',",
      "        'payload': { 'scope': 'moderation', 'key': f'flags:{author_id}',",
      "                     'value': (flags or 0) + 1 } })",
      '',
      "iii.register_function('content::on-flagged', on_flagged)",
      '',
      'iii.register_trigger({',
      "    'type': 'durable:subscriber',",
      "    'function_id': 'content::on-flagged',",
      "    'config': { 'topic': 'comment.review' },",
      '})',
    ],
    doneLabel: 'Deploy',
    delay: 300,
  },
  {
    id: 'status-3',
    type: 'status',
    variant: 'info',
    icon: 'connect',
    headline: 'State active',
    detail: 'Per-author flag counts persisted on every comment.review event',
    autoAdvance: 1400,
    delay: 200,
  },

  // ── Beat 4: Add HTTP ────────────────────────────────────────────────
  {
    id: 'msg-4',
    type: 'slack-message',
    sender: alex,
    content:
      'The frontend team needs a REST endpoint to submit content for moderation.',
    autoAdvance: 1500,
    delay: 500,
  },
  {
    id: 'reply-4',
    type: 'reply',
    content: 'No problem, we can add HTTP.',
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'terminal-4a',
    type: 'terminal-command',
    command: 'iii worker add iii-http',
    output: '✓ Worker iii-http installed',
    delay: 400,
  },
  {
    id: 'code-4',
    type: 'code-editor',
    filename: 'content-router.ts',
    language: 'typescript',
    lines: [
      'iii.registerFunction(',
      "  'http::submit-content',",
      '  async (payload: { body: { text: string; authorId: string } }) => {',
      '    const result = await iii.trigger({',
      "      function_id: 'content::route',",
      '      payload: payload.body,',
      '    })',
      '    return {',
      '      status_code: 200,',
      '      body: result,',
      "      headers: { 'Content-Type': 'application/json' },",
      '    }',
      '  },',
      ')',
      '',
      'iii.registerTrigger({',
      "  type: 'http',",
      "  function_id: 'http::submit-content',",
      "  config: { api_path: '/content/submit', http_method: 'POST' },",
      '})',
    ],
    doneLabel: 'Deploy',
    delay: 300,
  },
  {
    id: 'status-4',
    type: 'status',
    variant: 'info',
    icon: 'connect',
    headline: 'POST /content/submit',
    detail: 'HTTP endpoint live',
    autoAdvance: 1400,
    delay: 200,
  },

  // ── Beat 5: Punchline ───────────────────────────────────────────────
  {
    id: 'msg-5',
    type: 'slack-message',
    sender: alex,
    content: "Let me guess, it's already done?",
    autoAdvance: 1500,
    delay: 600,
  },
  {
    id: 'reply-5',
    type: 'reply',
    content: "Yup! It's a single system. Everything is already connected.",
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'status-5',
    type: 'status',
    variant: 'success',
    icon: 'check',
    headline: 'All services connected',
    detail: 'Every worker shares the same event bus and state',
    autoAdvance: 1600,
    delay: 200,
  },

  // ── Beat 6: Observability — debug a crashing dependency ─────────────
  {
    id: 'msg-6',
    type: 'slack-message',
    sender: alex,
    content:
      "We're seeing some classification requests fail intermittently. Can you investigate?",
    autoAdvance: 1500,
    delay: 500,
  },
  {
    id: 'reply-6',
    type: 'reply',
    content: 'Checking the traces now, should only take a moment.',
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'console-1',
    type: 'console-trace',
    traces: [
      { operation: 'content::route', duration: '2.4ms', status: 'ok' },
      { operation: 'content::classify', duration: '1.1ms', status: 'ok' },
      { operation: 'content::classify', status: 'error' },
    ],
    activeTraceIndex: 2,
    spans: [
      {
        label: 'content::route',
        duration: '6.22ms',
        widthPercent: 100,
        depth: 0,
        status: 'ok',
      },
      {
        label: 'content::classify',
        duration: '4.99ms',
        widthPercent: 80,
        depth: 1,
        status: 'ok',
      },
      {
        label: 'detoxify.predict',
        duration: '0.3ms',
        widthPercent: 8,
        depth: 2,
        status: 'error',
      },
    ],
    errorSpanIndex: 2,
    detail: {
      status: 'ERROR',
      service: 'content-classifier',
      error: 'detoxify 0.5.2 — RuntimeError: index out of range in self',
    },
    delay: 400,
  },
  {
    id: 'reply-7',
    type: 'reply',
    content:
      'Found it — known bug in detoxify 0.5.2. Bumping to 0.5.3 and restarting the worker.',
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'status-6a',
    type: 'status',
    variant: 'info',
    icon: 'deploy',
    headline: 'detoxify==0.5.2 → detoxify==0.5.3',
    detail: 'requirements.txt updated',
    autoAdvance: 1000,
    delay: 400,
  },
  {
    id: 'terminal-6b',
    type: 'terminal-command',
    command: 'iii worker stop content-classifier',
    output: '✓ Worker content-classifier stopped',
    delay: 300,
  },
  {
    id: 'terminal-6c',
    type: 'terminal-command',
    command: 'iii worker start content-classifier',
    output: '✓ Worker content-classifier started',
    delay: 300,
  },
  {
    id: 'status-6',
    type: 'status',
    variant: 'success',
    icon: 'observe',
    headline: 'Issue resolved',
    detail: 'Classifier restarted with detoxify==0.5.3',
    autoAdvance: 1600,
    delay: 200,
  },
];
