import type { Sender, Step } from './types';

const alex: Sender = {
  name: 'Alex',
  role: 'Product Lead',
};

export const homepageFlow: Step[] = [
  // ── Beat 1: Python classifier worker ────────────────────────────────
  {
    id: 'msg-1',
    type: 'slack-message',
    sender: alex,
    content:
      'We need to classify user-submitted content for toxicity before it goes live. Can you set something up?',
    action: { label: 'Start ticket' },
    delay: 500,
  },
  {
    id: 'reply-1',
    type: 'reply',
    content: "Sure, I'll write a Python classifier worker.",
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'code-1',
    type: 'code-editor',
    filename: 'content_classifier.py',
    language: 'python',
    lines: [
      'from iii import register_worker, InitOptions, Logger',
      '',
      "iii = register_worker(os.environ['III_ENGINE_URL'], InitOptions(",
      "    worker_name='content-classifier',",
      '))',
      'logger = Logger()',
      '',
      'def classify(payload: dict) -> dict:',
      "    text = payload.get('text', '')",
      "    logger.info(f'Classifying content: {text[:50]}...')",
      '    score = toxicity_model.predict(text)',
      "    return { 'label': 'toxic' if score > 0.7 else 'safe', 'score': score }",
      '',
      "iii.register_function('content::classify', classify)",
    ],
    doneLabel: 'Deploy',
    delay: 300,
  },
  {
    id: 'status-1',
    type: 'status',
    variant: 'info',
    icon: 'connect',
    headline: 'Classifier worker connected',
    detail: 'content::classify registered with the engine',
    autoAdvance: 1400,
    delay: 200,
  },

  // ── Beat 2: TS router, cross-language composition ───────────────────
  {
    id: 'msg-2',
    type: 'slack-message',
    sender: alex,
    content:
      'Great. Now we need to auto-approve clean content and flag toxic content for human review.',
    action: { label: 'View request' },
    delay: 500,
  },
  {
    id: 'reply-2',
    type: 'reply',
    content:
      "I'll create a TypeScript router that calls the classifier through the engine.",
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'code-2',
    type: 'code-editor',
    filename: 'content-router.ts',
    language: 'typescript',
    lines: [
      "import { registerWorker, Logger } from 'iii-sdk'",
      '',
      'const iii = registerWorker(process.env.III_ENGINE_URL, {',
      "  workerName: 'content-router',",
      '})',
      '',
      "iii.registerFunction('content::route', async ({ text, authorId }) => {",
      '  const { label, score } = await iii.trigger({',
      "    function_id: 'content::classify',",
      '    payload: { text },',
      '  })',
      '  return {',
      "    action: label === 'safe' ? 'published' : 'flagged',",
      '    score,',
      '  }',
      '})',
    ],
    doneLabel: 'Deploy',
    delay: 300,
  },
  {
    id: 'status-2',
    type: 'status',
    variant: 'info',
    icon: 'connect',
    headline: 'Content router live',
    detail: 'Classifying and routing cross-language via the engine',
    autoAdvance: 1400,
    delay: 200,
  },

  // ── Beat 3: Add state ───────────────────────────────────────────────
  {
    id: 'msg-3',
    type: 'slack-message',
    sender: alex,
    content:
      'Can we track how many times each author gets flagged? We need moderation history.',
    action: { label: 'View request' },
    delay: 500,
  },
  {
    id: 'reply-3',
    type: 'reply',
    content:
      "I'll add state — one command to enable the built-in state worker.",
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'code-3',
    type: 'code-editor',
    filename: 'content_classifier.py',
    language: 'python',
    lines: [
      'def classify(payload: dict) -> dict:',
      "    text, author_id = payload.get('text', ''), payload.get('author_id')",
      '    score = toxicity_model.predict(text)',
      "    label = 'toxic' if score > 0.7 else 'safe'",
      '',
      "    if label == 'toxic':",
      "        flags = iii.trigger({ 'function_id': 'state::get',",
      "            'payload': { 'scope': 'moderation', 'key': f'flags:{author_id}' } })",
      "        iii.trigger({ 'function_id': 'state::set',",
      "            'payload': { 'scope': 'moderation', 'key': f'flags:{author_id}',",
      "                         'value': (flags or 0) + 1 } })",
      '',
      "    return { 'label': label, 'score': score }",
    ],
    doneLabel: 'Deploy',
    delay: 300,
  },
  {
    id: 'status-3',
    type: 'status',
    variant: 'info',
    icon: 'connect',
    headline: 'State active',
    detail: 'Per-author flag counts persisted across every call',
    autoAdvance: 1400,
    delay: 200,
  },

  // ── Beat 4: Add HTTP ────────────────────────────────────────────────
  {
    id: 'msg-4',
    type: 'slack-message',
    sender: alex,
    content:
      'The frontend team needs a REST endpoint to submit content for moderation.',
    action: { label: 'View request' },
    delay: 500,
  },
  {
    id: 'reply-4',
    type: 'reply',
    content: 'Adding HTTP — one more built-in worker.',
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'code-4',
    type: 'code-editor',
    filename: 'content-router.ts',
    language: 'typescript',
    lines: [
      'iii.registerFunction(',
      "  'http::submit-content',",
      '  async (payload: { body: { text: string; authorId: string } }) => {',
      '    const result = await iii.trigger({',
      "      function_id: 'content::route',",
      '      payload: payload.body,',
      '    })',
      '    return {',
      '      status_code: 200,',
      '      body: result,',
      "      headers: { 'Content-Type': 'application/json' },",
      '    }',
      '  },',
      ')',
      '',
      'iii.registerTrigger({',
      "  type: 'http',",
      "  function_id: 'http::submit-content',",
      "  config: { api_path: '/content/submit', http_method: 'POST' },",
      '})',
    ],
    doneLabel: 'Deploy',
    delay: 300,
  },
  {
    id: 'status-4',
    type: 'status',
    variant: 'info',
    icon: 'connect',
    headline: 'HTTP endpoint live',
    detail: 'POST /content/submit routes through the full pipeline',
    autoAdvance: 1400,
    delay: 200,
  },

  // ── Beat 5: Punchline ───────────────────────────────────────────────
  {
    id: 'msg-5',
    type: 'slack-message',
    sender: alex,
    content:
      'Wait, the frontend can already see flag counts and everything? When did you wire that up?',
    action: { label: 'Reply' },
    delay: 600,
  },
  {
    id: 'reply-5',
    type: 'reply',
    content: "It's a single system. Everything is already connected.",
    sendLabel: 'Send',
    delay: 250,
  },
  {
    id: 'status-5',
    type: 'status',
    variant: 'success',
    icon: 'check',
    headline: 'All services connected',
    detail: 'Every worker shares the same event bus and state',
    autoAdvance: 1600,
    delay: 200,
  },
];
