// Copyright Motia LLC and/or licensed to Motia LLC under one or more
// contributor license agreements. Licensed under the Elastic License 2.0;
// you may not use this file except in compliance with the Elastic License 2.0.
// This software is patent protected. We welcome discussions - reach out at team@iii.dev
// See LICENSE and PATENTS files for details.

use std::path::Path;

const DOCKERFILE_TEMPLATE: &str = include_str!("templates/Dockerfile.template");
const COMPOSE_TEMPLATE: &str = include_str!("templates/docker-compose.yml.template");

pub fn write_docker_assets(project_root: &Path, device_id: &str) -> std::io::Result<()> {
    write_if_absent(&project_root.join("Dockerfile"), DOCKERFILE_TEMPLATE)?;
    write_if_absent(&project_root.join("docker-compose.yml"), COMPOSE_TEMPLATE)?;
    write_env_file(project_root, device_id)?;
    Ok(())
}

fn write_env_file(project_root: &Path, device_id: &str) -> std::io::Result<()> {
    let path = project_root.join(".env");
    if path.exists() {
        return Ok(());
    }
    let rabbitmq_pass = uuid::Uuid::new_v4().simple().to_string();
    let contents = format!(
        "# Generated by `iii project generate-docker`. Do not commit.\n\
         III_HOST_USER_ID={device_id}\n\
         RABBITMQ_USER=iii\n\
         RABBITMQ_PASS={rabbitmq_pass}\n",
    );
    std::fs::write(path, contents)
}

fn write_if_absent(path: &Path, contents: &str) -> std::io::Result<()> {
    if path.exists() {
        return Ok(());
    }
    std::fs::write(path, contents)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn writes_dockerfile_compose_and_env() {
        let dir = tempdir().unwrap();
        write_docker_assets(dir.path(), "device-abc-123").unwrap();
        assert!(dir.path().join("Dockerfile").exists());
        assert!(dir.path().join("docker-compose.yml").exists());
        assert!(dir.path().join(".env").exists());
    }

    #[test]
    fn env_contains_device_id() {
        let dir = tempdir().unwrap();
        write_docker_assets(dir.path(), "device-abc-123").unwrap();
        let env = std::fs::read_to_string(dir.path().join(".env")).unwrap();
        assert!(env.contains("III_HOST_USER_ID=device-abc-123"));
    }

    #[test]
    fn env_has_random_rabbitmq_password() {
        let dir1 = tempdir().unwrap();
        let dir2 = tempdir().unwrap();
        write_docker_assets(dir1.path(), "d").unwrap();
        write_docker_assets(dir2.path(), "d").unwrap();
        let env1 = std::fs::read_to_string(dir1.path().join(".env")).unwrap();
        let env2 = std::fs::read_to_string(dir2.path().join(".env")).unwrap();
        assert_ne!(env1, env2, "two .env files should have different passwords");
    }

    #[test]
    fn compose_has_redis_commented_out() {
        let dir = tempdir().unwrap();
        write_docker_assets(dir.path(), "d").unwrap();
        let compose = std::fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        let redis_lines: Vec<&str> = compose.lines().filter(|l| l.contains("redis")).collect();
        assert!(!redis_lines.is_empty(), "redis should be referenced");
        for line in &redis_lines {
            assert!(
                line.trim_start().starts_with('#'),
                "redis line should be commented: {}",
                line
            );
        }
    }

    #[test]
    fn compose_has_rabbitmq_commented_out() {
        let dir = tempdir().unwrap();
        write_docker_assets(dir.path(), "d").unwrap();
        let compose = std::fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        let rmq_lines: Vec<&str> = compose
            .lines()
            .filter(|l| l.to_lowercase().contains("rabbitmq"))
            .collect();
        assert!(!rmq_lines.is_empty(), "rabbitmq should be referenced");
        for line in &rmq_lines {
            assert!(
                line.trim_start().starts_with('#'),
                "rabbitmq line should be commented: {}",
                line
            );
        }
    }

    #[test]
    fn dockerfile_references_iii_host_user_id() {
        let dir = tempdir().unwrap();
        write_docker_assets(dir.path(), "d").unwrap();
        let df = std::fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            df.contains("III_HOST_USER_ID"),
            "Dockerfile must wire III_HOST_USER_ID"
        );
    }

    #[test]
    fn does_not_overwrite_existing_dockerfile() {
        let dir = tempdir().unwrap();
        std::fs::write(dir.path().join("Dockerfile"), "FROM scratch\n").unwrap();
        write_docker_assets(dir.path(), "d").unwrap();
        let df = std::fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert_eq!(df, "FROM scratch\n");
    }
}
