import { schemaToJsonSchema } from '../schema-utils'
import type { Step } from '../types'
import type { Stream } from '../types-stream'
import { generateTypeFromSchema } from './generate-type-from-schema'

export const generateStreamsInterface = (streams: Record<string, Stream>): string => {
  const entries = Object.entries(streams)
    .filter(([_, stream]) => !stream.hidden)
    .map(([name, stream]) => {
      const jsonSchema = schemaToJsonSchema(stream.config.schema)
      const type = jsonSchema ? generateTypeFromSchema(jsonSchema) : 'unknown'
      return `    ${name}: MotiaStream<${type}>`
    })

  return entries.length > 0 ? `  interface Streams {\n${entries.join('\n')}\n  }` : `  interface Streams {}`
}

export const generateEnqueuesInterface = (steps: Step[]): string => {
  const enqueueTypes: Record<string, string> = {}

  for (const step of steps) {
    if (step.config.enqueues) {
      step.config.enqueues.forEach((enqueue) => {
        const topic = typeof enqueue === 'string' ? enqueue : enqueue.topic
        if (!enqueueTypes[topic]) {
          enqueueTypes[topic] = 'unknown'
        }
      })
    }

    for (const trigger of step.config.triggers) {
      if (trigger.type === 'queue') {
        const topic = trigger.topic
        if (!enqueueTypes[topic] && trigger.input) {
          const jsonSchema = schemaToJsonSchema(trigger.input)
          const type = jsonSchema ? generateTypeFromSchema(jsonSchema) : 'unknown'
          enqueueTypes[topic] = type
        }
      }
    }
  }

  const entries = Object.entries(enqueueTypes).map(([topic, type]) => `    '${topic}': ${type}`)

  return entries.length > 0 ? `  interface Enqueues {\n${entries.join('\n')}\n  }` : `  interface Enqueues {}`
}

export const generateTypesString = (steps: Step[], streams: Record<string, Stream>): string => {
  const streamsInterface = generateStreamsInterface(streams)
  const enqueuesInterface = generateEnqueuesInterface(steps)

  return `/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 */
import { MotiaStream } from 'motia'

declare module 'motia' {
${streamsInterface}

${enqueuesInterface}
}
`
}
