import type { HttpInvocationConfig } from '@iii-dev/helpers/http'

/**
 * Any JSON value: the TypeScript equivalent of the engine's arbitrary-JSON
 * wire values (Rust `serde_json::Value`). Used where the wire contract is
 * "any JSON", e.g. per-invocation `metadata`.
 */
export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue }

export enum MessageType {
  RegisterFunction = 'registerfunction',
  UnregisterFunction = 'unregisterfunction',
  InvokeFunction = 'invokefunction',
  InvocationResult = 'invocationresult',
  RegisterTriggerType = 'registertriggertype',
  RegisterTrigger = 'registertrigger',
  UnregisterTrigger = 'unregistertrigger',
  UnregisterTriggerType = 'unregistertriggertype',
  TriggerRegistrationResult = 'triggerregistrationresult',
  WorkerRegistered = 'workerregistered',
  RegistrationRejected = 'registrationrejected',
}

export type RegisterTriggerTypeMessage = {
  message_type: MessageType.RegisterTriggerType
  /** Unique identifier for the trigger type (e.g. `state`, `durable:subscriber`). */
  id: string
  /** Human-readable description of what this trigger type does. */
  description: string
}

export type UnregisterTriggerTypeMessage = {
  message_type: MessageType.UnregisterTriggerType
  id: string
}

export type UnregisterTriggerMessage = {
  message_type: MessageType.UnregisterTrigger
  id: string
  type?: string
}

export type ErrorBody = {
  code: string
  message: string
  stacktrace?: string
}

export type TriggerRegistrationResultMessage = {
  message_type: MessageType.TriggerRegistrationResult
  id: string
  type: string
  function_id: string
  error?: ErrorBody
}

export type RegisterTriggerMessage = {
  /** Wire discriminator; always `MessageType.RegisterTrigger`. */
  message_type: MessageType.RegisterTrigger
  /** Unique trigger identifier, generated by the SDK during registration. */
  id: string
  /** Identifier of the registered trigger type this trigger uses (e.g. `storage::object-created`, `http`). */
  type: string
  /** ID of the function this trigger invokes when it fires. */
  function_id: string
  /** Trigger-type-specific configuration, matching the shape the trigger type expects. */
  config: unknown
  /** Arbitrary user-specifiable metadata supplied to the triggered handler function on every invocation. */
  metadata?: Record<string, unknown>
}

export type RegisterFunctionFormat = {
  /**
   * The name of the parameter.
   */
  name?: string
  /**
   * The description of the parameter.
   */
  description?: string
  /**
   * The type of the parameter.
   */
  type?: 'string' | 'number' | 'boolean' | 'object' | 'array' | 'null' | 'map' | 'integer'
  /**
   * The body of the parameter (for objects).
   */
  properties?: Record<string, unknown>
  /**
   * The items of the parameter (for arrays).
   */
  items?: unknown
  /**
   * Whether the parameter is required.
   */
  required?: string[]
  [key: string]: unknown
}

export type RegisterFunctionMessage = {
  message_type: MessageType.RegisterFunction
  /**
   * The path of the function (use :: for namespacing, e.g. external::my_lambda).
   */
  id: string
  /**
   * The description of the function.
   */
  description?: string
  /**
   * The request format of the function.
   */
  request_format?: RegisterFunctionFormat
  /**
   * The response format of the function.
   */
  response_format?: RegisterFunctionFormat
  /**
   * Arbitrary metadata attached to the function.
   */
  metadata?: Record<string, unknown>
  /**
   * HTTP invocation config for external HTTP functions (Lambda, Cloudflare Workers, etc.).
   */
  invocation?: HttpInvocationConfig
}

/**
 * Routing action for {@link TriggerRequest}. Determines how the engine
 * handles the invocation.
 *
 * - `enqueue`: Routes through a named queue for async processing.
 * - `void`: Fire-and-forget, no response.
 */
export type TriggerAction = { type: 'enqueue'; queue: string } | { type: 'void' }

/**
 * Input passed to the RBAC middleware function on every function invocation
 * through the RBAC port. The middleware can inspect, modify, or reject the
 * call before it reaches the target function.
 */
export type MiddlewareFunctionInput = {
  /** ID of the function being invoked. */
  function_id: string
  /** Payload sent by the caller. */
  payload: Record<string, unknown>
  /** Routing action, if any. */
  action?: TriggerAction
  /** Auth context returned by the auth function for this session. */
  context: Record<string, unknown>
}

/**
 * Request object passed to {@link IIIClient.trigger}.
 *
 * @typeParam TInput - Type of the payload.
 */
export type TriggerRequest<TInput = unknown> = {
  /** ID of the function to invoke. */
  function_id: string
  /** Input data passed to the function. */
  payload: TInput
  /** Sets how the trigger is routed. Omit for a synchronous request/response. Specify for a specific routing scheme (e.g. `TriggerAction.Enqueue()`, `TriggerAction.Void()`). */
  action?: TriggerAction
  /** Override the default invocation timeout, in milliseconds. */
  timeoutMs?: number
  /** Arbitrary user-specifiable metadata supplied to the triggered handler function on every invocation. */
  metadata?: unknown
  /**
   * Target namespace for routing. Omit to route within the engine's default
   * namespace. Serialized into the {@link InvokeFunctionMessage} `namespace`
   * field; omitted from the wire when undefined.
   */
  namespace?: string
}

export type InvokeFunctionMessage = {
  message_type: MessageType.InvokeFunction
  /**
   * This is optional for async invocations
   */
  invocation_id?: string
  /**
   * The path of the function.
   */
  function_id: string
  /**
   * The data to pass to the function
   */
  data: unknown
  /**
   * W3C trace-context traceparent header for distributed tracing
   */
  traceparent?: string
  /**
   * W3C baggage header for cross-cutting context propagation
   */
  baggage?: string
  /**
   * Trigger action for queue routing or fire-and-forget
   */
  action?: TriggerAction
  /**
   * Optional per-invocation metadata (arbitrary JSON). Travels as a separate
   * channel from `data`. Omitted from the JSON when undefined; absence on
   * inbound means "no metadata" (backward compatible with older engines).
   */
  metadata?: JsonValue
  /**
   * Target namespace for routing. Optional and additive: omitted from the JSON
   * when undefined, and absence on inbound means the engine's default
   * namespace (backward compatible with older engines).
   */
  namespace?: string
}

export type InvocationResultMessage = {
  message_type: MessageType.InvocationResult
  /**
   * The id of the invocation
   */
  invocation_id: string
  /**
   * The path of the function.
   */
  function_id: string
  result?: unknown
  error?: unknown
  /**
   * W3C trace-context traceparent header for distributed tracing
   */
  traceparent?: string
  /**
   * W3C baggage header for cross-cutting context propagation
   */
  baggage?: string
}

export type WorkerRegisteredMessage = {
  message_type: MessageType.WorkerRegistered
  worker_id: string
}

/**
 * Sent by the engine when this worker's registration collides with a live
 * worker already owning the same `worker_name` (or an exported function id)
 * in `namespace`. The engine closes the connection after sending it, so the
 * SDK treats it as fatal: it stops the worker and does not reconnect.
 */
export type RegistrationRejectedMessage = {
  message_type: MessageType.RegistrationRejected
  /** Machine-readable rejection code (e.g. `worker_name_conflict`). */
  code: string
  /** Namespace in which the collision occurred. */
  namespace: string
  /** The worker name that was rejected. */
  worker_name: string
  /** ID of the live worker that already owns the contested identity. */
  owner_worker_id: string
}

export type UnregisterFunctionMessage = {
  message_type: MessageType.UnregisterFunction
  id: string
}

/**
 * Serializable reference to one end of a streaming channel. Can be included
 * in invocation payloads to pass channel endpoints between workers.
 */
export type StreamChannelRef = {
  /** Unique channel identifier. */
  channel_id: string
  /** Access key for authentication. */
  access_key: string
  /** Whether this ref is for reading or writing. */
  direction: 'read' | 'write'
}

export type IIIMessage =
  | RegisterFunctionMessage
  | UnregisterFunctionMessage
  | InvokeFunctionMessage
  | InvocationResultMessage
  | RegisterTriggerMessage
  | RegisterTriggerTypeMessage
  | UnregisterTriggerMessage
  | UnregisterTriggerTypeMessage
  | TriggerRegistrationResultMessage
  | WorkerRegisteredMessage
  | RegistrationRejectedMessage
