/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriggersRouteImport } from './routes/triggers'
import { Route as TracesRouteImport } from './routes/traces'
import { Route as StreamsRouteImport } from './routes/streams'
import { Route as StatesRouteImport } from './routes/states'
import { Route as QueuesRouteImport } from './routes/queues'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as FunctionsRouteImport } from './routes/functions'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as DeadLetterRouteImport } from './routes/dead-letter'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as IndexRouteImport } from './routes/index'

const TriggersRoute = TriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsRoute = StreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesRoute = QueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const FunctionsRoute = FunctionsRouteImport.update({
  id: '/functions',
  path: '/functions',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadLetterRoute = DeadLetterRouteImport.update({
  id: '/dead-letter',
  path: '/dead-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/dead-letter': typeof DeadLetterRoute
  '/flow': typeof FlowRoute
  '/functions': typeof FunctionsRoute
  '/logs': typeof LogsRoute
  '/queues': typeof QueuesRoute
  '/states': typeof StatesRoute
  '/streams': typeof StreamsRoute
  '/traces': typeof TracesRoute
  '/triggers': typeof TriggersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/dead-letter': typeof DeadLetterRoute
  '/flow': typeof FlowRoute
  '/functions': typeof FunctionsRoute
  '/logs': typeof LogsRoute
  '/queues': typeof QueuesRoute
  '/states': typeof StatesRoute
  '/streams': typeof StreamsRoute
  '/traces': typeof TracesRoute
  '/triggers': typeof TriggersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/dead-letter': typeof DeadLetterRoute
  '/flow': typeof FlowRoute
  '/functions': typeof FunctionsRoute
  '/logs': typeof LogsRoute
  '/queues': typeof QueuesRoute
  '/states': typeof StatesRoute
  '/streams': typeof StreamsRoute
  '/traces': typeof TracesRoute
  '/triggers': typeof TriggersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/dead-letter'
    | '/flow'
    | '/functions'
    | '/logs'
    | '/queues'
    | '/states'
    | '/streams'
    | '/traces'
    | '/triggers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/dead-letter'
    | '/flow'
    | '/functions'
    | '/logs'
    | '/queues'
    | '/states'
    | '/streams'
    | '/traces'
    | '/triggers'
  id:
    | '__root__'
    | '/'
    | '/config'
    | '/dead-letter'
    | '/flow'
    | '/functions'
    | '/logs'
    | '/queues'
    | '/states'
    | '/streams'
    | '/traces'
    | '/triggers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  DeadLetterRoute: typeof DeadLetterRoute
  FlowRoute: typeof FlowRoute
  FunctionsRoute: typeof FunctionsRoute
  LogsRoute: typeof LogsRoute
  QueuesRoute: typeof QueuesRoute
  StatesRoute: typeof StatesRoute
  StreamsRoute: typeof StreamsRoute
  TracesRoute: typeof TracesRoute
  TriggersRoute: typeof TriggersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triggers': {
      id: '/triggers'
      path: '/triggers'
      fullPath: '/triggers'
      preLoaderRoute: typeof TriggersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams': {
      id: '/streams'
      path: '/streams'
      fullPath: '/streams'
      preLoaderRoute: typeof StreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues': {
      id: '/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof QueuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions': {
      id: '/functions'
      path: '/functions'
      fullPath: '/functions'
      preLoaderRoute: typeof FunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dead-letter': {
      id: '/dead-letter'
      path: '/dead-letter'
      fullPath: '/dead-letter'
      preLoaderRoute: typeof DeadLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  DeadLetterRoute: DeadLetterRoute,
  FlowRoute: FlowRoute,
  FunctionsRoute: FunctionsRoute,
  LogsRoute: LogsRoute,
  QueuesRoute: QueuesRoute,
  StatesRoute: StatesRoute,
  StreamsRoute: StreamsRoute,
  TracesRoute: TracesRoute,
  TriggersRoute: TriggersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
